// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserbalanceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebaseuserMw() []app.HandlerFunc {
	// your code...
	return nil
}
