// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	category "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/category"
	home "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/home"
	product "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/product"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	category.Register(r)

	product.Register(r)

	home.Register(r)
}
