// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	// order "douyin-gomall/gomall/app/hertz_gateway/biz/router/order"
	order "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/order"
	home "github.com/PiaoAdmin/gomall/app/hertz_gateway/biz/router/home"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	order.Register(r)

	home.Register(r)
}
