// Code generated by Kitex v0.9.1. DO NOT EDIT.

package authservice

import (
	"context"
	auth "github.com/PiaoAdmin/gomall/rpc_gen/kitex_gen/auth"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	IssueToken(ctx context.Context, Req *auth.IssueTokenRequest, callOptions ...callopt.Option) (r *auth.IssueTokenResponse, err error)
	VerifyToken(ctx context.Context, Req *auth.VerifyTokenRequest, callOptions ...callopt.Option) (r *auth.VerifyTokenResponse, err error)
	RefreshToken(ctx context.Context, Req *auth.RefreshTokenRequest, callOptions ...callopt.Option) (r *auth.RefreshTokenResponse, err error)
	Logout(ctx context.Context, Req *auth.LogoutRequest, callOptions ...callopt.Option) (r *auth.LogoutResponse, err error)
	CheckPermission(ctx context.Context, Req *auth.PermissionCheckRequest, callOptions ...callopt.Option) (r *auth.PermissionCheckResponse, err error)
	AddUserRole(ctx context.Context, Req *auth.AddUserRoleRequest, callOptions ...callopt.Option) (r *auth.AddUserRoleResponse, err error)
	RemoveUserRole(ctx context.Context, Req *auth.RemoveUserRoleRequest, callOptions ...callopt.Option) (r *auth.RemoveUserRoleResponse, err error)
	GetUserRole(ctx context.Context, Req *auth.GetUserRoleRequest, callOptions ...callopt.Option) (r *auth.GetUserRoleResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAuthServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAuthServiceClient struct {
	*kClient
}

func (p *kAuthServiceClient) IssueToken(ctx context.Context, Req *auth.IssueTokenRequest, callOptions ...callopt.Option) (r *auth.IssueTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.IssueToken(ctx, Req)
}

func (p *kAuthServiceClient) VerifyToken(ctx context.Context, Req *auth.VerifyTokenRequest, callOptions ...callopt.Option) (r *auth.VerifyTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VerifyToken(ctx, Req)
}

func (p *kAuthServiceClient) RefreshToken(ctx context.Context, Req *auth.RefreshTokenRequest, callOptions ...callopt.Option) (r *auth.RefreshTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefreshToken(ctx, Req)
}

func (p *kAuthServiceClient) Logout(ctx context.Context, Req *auth.LogoutRequest, callOptions ...callopt.Option) (r *auth.LogoutResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, Req)
}

func (p *kAuthServiceClient) CheckPermission(ctx context.Context, Req *auth.PermissionCheckRequest, callOptions ...callopt.Option) (r *auth.PermissionCheckResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckPermission(ctx, Req)
}

func (p *kAuthServiceClient) AddUserRole(ctx context.Context, Req *auth.AddUserRoleRequest, callOptions ...callopt.Option) (r *auth.AddUserRoleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddUserRole(ctx, Req)
}

func (p *kAuthServiceClient) RemoveUserRole(ctx context.Context, Req *auth.RemoveUserRoleRequest, callOptions ...callopt.Option) (r *auth.RemoveUserRoleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveUserRole(ctx, Req)
}

func (p *kAuthServiceClient) GetUserRole(ctx context.Context, Req *auth.GetUserRoleRequest, callOptions ...callopt.Option) (r *auth.GetUserRoleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserRole(ctx, Req)
}
